# Generated by Django 5.0.6 on 2024-08-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_image_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='emojie',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
